### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by mattwietrzyk** [kamawietrzyk/czaryMarry#15]
Przy rozdzielczosci 1920x1200 rozjezdza zdaja sie imiona.
![Onas1](https://user-images.githubusercontent.com/31667641/107964853-0c837f80-6faa-11eb-821e-103e61c39861.png)
![Onas2](https://user-images.githubusercontent.com/31667641/107964857-0db4ac80-6faa-11eb-9cb7-8e5849b1b61e.png)

**Comment by kamawietrzyk** [comment]
![Zrzut ekranu 2021-02-15 o 18 53 26](https://user-images.githubusercontent.com/44195056/107979587-211e4280-6fbf-11eb-8357-b18401cc081a.png)
@mattwietrzyk poprawione
