### ISSUE TITLE
Landing - warszawa

### ISSUE THREAD

**Issue by mattwietrzyk** [kamawietrzyk/czaryMarry#16]
W Landingu Warszawa:
Dociagnac tekst do szczytu zdjecia.
![Warszawa_Landing](https://user-images.githubusercontent.com/31667641/107965362-bcf18380-6faa-11eb-8a68-fbccdd762dd0.png)
zrobic wieszy spacing pomiedzy naglowkiem a wykropkowaniem. Czcionka lepiej zeby byla takiej samej wielkosci jak reszta. 
![Waszawa_linia](https://user-images.githubusercontent.com/31667641/107965367-bebb4700-6faa-11eb-9206-979291f73e71.png)

**Comment by kamawietrzyk** [comment]
![Zrzut ekranu 2021-02-15 o 19 05 50](https://user-images.githubusercontent.com/44195056/107980618-e3bab480-6fc0-11eb-8bd4-542307350aed.png)
![Zrzut ekranu 2021-02-15 o 19 06 01](https://user-images.githubusercontent.com/44195056/107980623-e4ebe180-6fc0-11eb-94d6-1457caef3138.png)

@mattwietrzyk done
