### ISSUE TITLE
Realizacje

### ISSUE THREAD

**Issue by mattwietrzyk** [kamawietrzyk/czaryMarry#17]
Rozdzielczosc: 1980x1080
http://new.czarymarry.com/realizacje

Rozjezdzaja sie realizacje dopiero na 1680x1050 jest ok
![NaszePary1](https://user-images.githubusercontent.com/31667641/107966120-b283b980-6fab-11eb-9ab1-6341660484cf.png)
![NaszePary2](https://user-images.githubusercontent.com/31667641/107966125-b31c5000-6fab-11eb-96e9-b3df593a92c4.png)

**Comment by kamawietrzyk** [comment]
![Zrzut ekranu 2021-02-15 o 19 16 44](https://user-images.githubusercontent.com/44195056/107981455-61cb8b00-6fc2-11eb-9d1c-8ad65f45e9fa.png)
@mattwietrzyk poprawione
