### ISSUE TITLE
Jak Pracujemy

### ISSUE THREAD

**Issue by mattwietrzyk** [kamawietrzyk/czaryMarry#18]
Rozdzielczosc: 1980x1080
http://new.czarymarry.com/jak-pracujemy

na 1680x1050 jest ok. Tak powinno wygladac niezaleznie juz od rozdzielczosci. W sesie wieksze równe 1680x1050

![Jak pracujemy](https://user-images.githubusercontent.com/31667641/107966475-3342b580-6fac-11eb-93d2-c0178085e00c.png)

**Comment by kamawietrzyk** [comment]
![Zrzut ekranu 2021-02-15 o 19 26 50](https://user-images.githubusercontent.com/44195056/107982134-cc30fb00-6fc3-11eb-9628-f9fefe8534f6.png)

@mattwietrzyk poprawione
