### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by mattwietrzyk** [kamawietrzyk/czaryMarry#19]
przy rozdzielczosci 1980x1200 jest na srodku, troche wyglada jak scisniety. Again 1680x1050 jest dobrze i tak powinno wygladac
![kontakt](https://user-images.githubusercontent.com/31667641/107966871-b9f79280-6fac-11eb-9d81-5dcf366a86c1.png)

**Comment by kamawietrzyk** [comment]
![Zrzut ekranu 2021-02-15 o 19 45 28](https://user-images.githubusercontent.com/44195056/107983586-65611100-6fc6-11eb-885e-3ecb51ef2563.png)

@mattwietrzyk poprawione
