### ISSUE TITLE
Kontakt - spacing miedzy ikonami

### ISSUE THREAD

**Issue by mattwietrzyk** [kamawietrzyk/czaryMarry#20]
spacing miedzy ikonami spolecznosciowymi nie jest taki sam. Na pewno nie jest pomiedzy Facebook a reszta. Reszta chyba ok.
![kontakt1](https://user-images.githubusercontent.com/31667641/107967271-325e5380-6fad-11eb-9e7e-359450c745d0.png)

**Comment by kamawietrzyk** [comment]
@mattwietrzyk poprawione
