### ISSUE TITLE
Kontakt - walidacja

### ISSUE THREAD

**Issue by mattwietrzyk** [kamawietrzyk/czaryMarry#21]
Strona kontaktu powinna miec walidacje pól:
Imię, E-mail, Wiadomość to pola wymagane. 

Kliknięcie w wyślij bez uzupełniania pół powinno wywołać tooptip przy tych polach (albo w inpucie tych pól) 
z wiadomością "To pole jest wymagane"

Dodatkowo adres e-mail powinien miec walidacje poprawnosci adresu. Jesli ktos wpisze mateusz.wietrzyk.com
to powinien sie pojawic komunikat "Nieprawidłowy adres e-mail"

**Comment by kamawietrzyk** [comment]
@mattwietrzyk tam jest walidacja - button pozostaje nieaktywny do momentu wypełnienia wszystkich pól wymaganych. 
Email też ma walidację poprawności:

![Zrzut ekranu 2021-02-15 o 18 12 56](https://user-images.githubusercontent.com/44195056/107976284-99820500-6fb9-11eb-9610-a27f4fc53013.png)

Ale jeśli nie jest to wystarczające to postaram się do dopracować:)

**Comment by kamawietrzyk** [comment]
@mattwietrzyk dodałam '*' do pól wymaganych (wyrzuciłam 'temat' z wymaganych) i dorzuciłam loader na buttona jak formularz się wysyła. Dam znać jak pójdzie commit to sprawdź proszę czy tak będzie ok.
