### ISSUE TITLE
Nasze pary - picture loading. 

### ISSUE THREAD

**Issue by mattwietrzyk** [kamawietrzyk/czaryMarry#23]
http://new.czarymarry.com/realizacje

cos jest nie tak z ladowaniem sie zdjec. Przez klika sekund ekran przeskakuje jakby byla kolejnosc ladowania. Da sie to jakos poprawic?

**Comment by jaaaco** [comment]
@kamawietrzyk można wprowadzić do OurCouplesSlider state'a `isLoading` i specjalne komplnenty zamiast `<img>` użyć takiego komponentu https://www.npmjs.com/package/react-lazy-load-image-component

**Comment by kamawietrzyk** [comment]
@jaaaco dzięki, sprawdzę to świeżym mózgiem jutro. Na dziś wyłączyłam lazyLoad ze slick-slider'a i jest jakby lepiej, u mnie działa ;)
